DROP TABLE
  IF EXISTS {{TABLENAME}};

CREATE TABLE
  IF NOT EXISTS {{TABLENAME}} (
   {{COLUMNS_SCRIPTS}},
   ETL_TIMESTAMP TIMESTAMP 
  ) COMMENT '{{COMMENT}}' ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' LINES TERMINATED BY '\n' STORED AS TEXTFILE;