WITH
  O_ODS AS (
    SELECT
      *
    FROM
      ODS_HBCORE_{{TABLENAME}}
    WHERE
      ds IN (
        SELECT
          DISTINCT {{PRATITION}} 
        FROM
          STG_HBCORE_{{TABLENAME}}
      )
  ) 
 INSERT OVERWRITE ODS_HBCORE_{{TABLENAME}} PARTITION(DS)
SELECT
  ODS.*
FROM
  O_ODS ODS
  LEFT JOIN STG_HBCORE_{{TABLENAME}} STG ON {{LINKCOLUMNS}}
WHERE
  STG.{{id}} IS NULL
UNION ALL
SELECT
  STG.*,
  {{PRATITION}} AS DS
FROM
  STG_HBCORE_{{TABLENAME}} STG